defaults:  
  - _self_  
  - model: base
  - data: 7scenes_visloc
  - cluster: local
  
hydra:  
  # Disable creation of sub-directories for each run
  output_subdir: null  
  # Disable changing work directory to run sub-directory
  run:  
    dir: .
  
device: cuda
use_map_cameras: false
use_query_intrinsics: false
output_dir: null
align_sim3: false
num_workers: 8

patch_size: 14
target_img_size: 518

map_kwargs: {}
